# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
